### PR TITLE
Allow DNS env values to be set at runtime without having to rebuild image

### LINKED ISSUE #28: Custom DNS server are not respected at runtime
Default `$DNS` values are currently hard coded into the docker build, and only the `$UPSTREAM` variables are set dynamically at runtime.

### PR DESCRIPTION
**Pull request by nathang21**
I discovered when testing that setting custom  DNS variables were not respected at runtime. 
- Allow $DNS env variables to be customized and used at runtime: Fixes #28 
- Remove $UPSTREAM env in favor of the easily modifiable $DNS variables
- Adding steps for building and testing locally
- Fix typo in $ADDRESS variable example

### CODE REVIEW

**Comment by nathang21** [comment]
Docker login errors are back (don't have access to retry the build).
https://travis-ci.org/github/visibilityspots/dockerfile-cloudflared/builds/738122696

Also seems like the matrix is not working anymore, only seeing 1 job for each build, instead of the 4 previously (3 builds for each arch, then 1 docker push)

**Comment by nathang21** [comment]
@visibilityspots Can you try re-running the CI, I don't see anything that would have caused it to fail, seems like it might be a transient issue, unless your rotated the dockerhub tokens again.

**Review by visibilityspots — COMMENTED** [review]
I added the UPSTREAM parameter as a PR (https://github.com/visibilityspots/dockerfile-cloudflared/pull/14) a while back. This made it possible to change the upstream when desired.

**Comment by nathang21** [comment]
Ah I didn't even think about using DoH with non-standard upstream urls. I assumed this syntax was standard `https://${DNS}/.well-known/dns-query` and only the DNS domain needed to change.

I will re-work this PR to support both. The main issue I am trying to solve is #28 so these can be values modified more easily without rebuilding the container.

**Comment by visibilityspots** [comment]
I merged DNS and UPSTREAM parameters into one parameter to keep it a bit less complex. Therefore this pull request isn't needed anymore?

**Pull request closed without merging**
